"""add jobs_raw and sync_metadata tables

Revision ID: 0254efb46e5b
Revises: cfc317f631ce
Create Date: 2026-07-17 14:37:54.064721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0254efb46e5b'
down_revision: Union[str, Sequence[str], None] = 'cfc317f631ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_raw',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('minimum_experience', sa.String(length=50), nullable=True),
    sa.Column('maximum_experience', sa.String(length=50), nullable=True),
    sa.Column('minimum_qualification', sa.String(length=255), nullable=True),
    sa.Column('preffered_qualification', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('job_location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('job_status', sa.Boolean(), nullable=False),
    sa.Column('jobs_posted_status', sa.String(length=50), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('jd_processed', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('sync_metadata',
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('entity_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_metadata')
    op.drop_table('jobs_raw')
    # ### end Alembic commands ###
