"""Add api_keys table

Revision ID: 330518d0cfaa
Revises: baff37103137
Create Date: 2026-08-13 10:42:56.765400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330518d0cfaa'
down_revision: Union[str, Sequence[str], None] = 'baff37103137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_index(op.f('idx_candidate_job_unique'), table_name='candidate_job_scores')
    op.drop_index(op.f('idx_cjs_job_overall_null'), table_name='candidate_job_scores', postgresql_where='(overall_score IS NULL)')
    op.drop_index(op.f('idx_cjs_job_semantic_null'), table_name='candidate_job_scores', postgresql_where='(semantic_score IS NULL)')
    op.drop_index(op.f('idx_resume_embedding_hnsw'), table_name='resume_processed', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_resume_embedding_hnsw'), 'resume_processed', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_cjs_job_semantic_null'), 'candidate_job_scores', ['job_id'], unique=False, postgresql_where='(semantic_score IS NULL)')
    op.create_index(op.f('idx_cjs_job_overall_null'), 'candidate_job_scores', ['job_id'], unique=False, postgresql_where='(overall_score IS NULL)')
    op.create_index(op.f('idx_candidate_job_unique'), 'candidate_job_scores', ['candidate_id', 'job_id'], unique=True)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
