"""add jd_hash to job_processed

Revision ID: 4239acaa891b
Revises: ae669cf0e2de
Create Date: 2026-07-22 11:38:21.794856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4239acaa891b'
down_revision: Union[str, Sequence[str], None] = 'ae669cf0e2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_processed', sa.Column('jd_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_processed', 'jd_hash')
    # ### end Alembic commands ###
