"""add resume_processed table

Revision ID: 4aac91d050ec
Revises: 0254efb46e5b
Create Date: 2026-07-21 16:32:17.755806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aac91d050ec'
down_revision: Union[str, Sequence[str], None] = '0254efb46e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_processed',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.Text(), nullable=True),
    sa.Column('resume_hash', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_processed')
    # ### end Alembic commands ###
