"""add skills_extraction_uncertain flag

Revision ID: 68f1391d47cf
Revises: fa9eac278162
Create Date: 2026-08-17 14:05:37.022289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f1391d47cf'
down_revision: Union[str, Sequence[str], None] = 'fa9eac278162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'job_processed',
        sa.Column(
            'skills_extraction_uncertain',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.alter_column('job_processed', 'skills_extraction_uncertain', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_processed', 'skills_extraction_uncertain')
    # ### end Alembic commands ###
