"""add job_processed table

Revision ID: ae669cf0e2de
Revises: 4aac91d050ec
Create Date: 2026-07-22 11:24:38.007706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae669cf0e2de'
down_revision: Union[str, Sequence[str], None] = '4aac91d050ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_processed',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cleaned_jd', sa.Text(), nullable=True),
    sa.Column('structured_json', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_processed')
    # ### end Alembic commands ###
