"""add embedding_similarity and llm_reviewed columns

Revision ID: baff37103137
Revises: 27d8568c8b46
Create Date: 2026-07-30 15:11:09.685930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baff37103137'
down_revision: Union[str, Sequence[str], None] = '27d8568c8b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('candidate_job_scores', sa.Column('embedding_similarity', sa.Float(), nullable=True))
    
    op.add_column(
    'candidate_job_scores',
    sa.Column('llm_reviewed', sa.Boolean(), nullable=False, server_default=sa.false())
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_job_scores', 'llm_reviewed')
    op.drop_column('candidate_job_scores', 'embedding_similarity')
    # ### end Alembic commands ###
