"""create candidate_raw table

Revision ID: cfc317f631ce
Revises: 8515b8ddc843
Create Date: 2026-07-17 14:15:22.848981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfc317f631ce'
down_revision: Union[str, Sequence[str], None] = '8515b8ddc843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_raw',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('current_designation', sa.String(length=255), nullable=True),
    sa.Column('currently_working_company_name', sa.String(length=255), nullable=True),
    sa.Column('key_experience', sa.String(length=100), nullable=True),
    sa.Column('key_experience_in_month', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('resume_file_name', sa.String(length=500), nullable=True),
    sa.Column('resume_file_url', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('candidate_type', sa.String(length=50), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('resume_processed', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.drop_index(op.f('ix_processed_tracker_candidate_id'), table_name='processed_tracker')
    op.drop_index(op.f('ix_processed_tracker_job_id'), table_name='processed_tracker')
    op.drop_table('processed_tracker')
    op.drop_table('candidate_resume_cache')
    op.drop_index(op.f('ix_job_recommendations_job_id'), table_name='job_recommendations')
    op.drop_table('job_recommendations')
    op.drop_table('job_description_cache')
    op.drop_table('sync_cursor')
    op.drop_table('scoring_logs')
    op.drop_index(op.f('ix_candidate_scores_candidate_id'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_final_score'), table_name='candidate_scores')
    op.drop_index(op.f('ix_candidate_scores_job_id'), table_name='candidate_scores')
    op.drop_table('candidate_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('skills_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tech_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('experience_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('education_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('semantic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('contextual_fit_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('candidate_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('job_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_scores_pkey'))
    )
    op.create_index(op.f('ix_candidate_scores_job_id'), 'candidate_scores', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_scores_final_score'), 'candidate_scores', ['final_score'], unique=False)
    op.create_index(op.f('ix_candidate_scores_candidate_id'), 'candidate_scores', ['candidate_id'], unique=False)
    op.create_table('scoring_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('run_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('jobs_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidates_scored', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scoring_logs_pkey'))
    )
    op.create_table('sync_cursor',
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_synced_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('table_name', name=op.f('sync_cursor_pkey'))
    )
    op.create_table('job_description_cache',
    sa.Column('job_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_description_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('work_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('required_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cached_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('job_id', name=op.f('job_description_cache_pkey'))
    )
    op.create_table('job_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('job_recommendations_pkey'))
    )
    op.create_index(op.f('ix_job_recommendations_job_id'), 'job_recommendations', ['job_id'], unique=False)
    op.create_table('candidate_resume_cache',
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('resume_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('parse_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('parse_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('candidate_id', name=op.f('candidate_resume_cache_pkey'))
    )
    op.create_table('processed_tracker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_tracker_pkey'))
    )
    op.create_index(op.f('ix_processed_tracker_job_id'), 'processed_tracker', ['job_id'], unique=False)
    op.create_index(op.f('ix_processed_tracker_candidate_id'), 'processed_tracker', ['candidate_id'], unique=False)
    op.drop_table('candidate_raw')
    # ### end Alembic commands ###
