"""add score_source field

Revision ID: ddb481e3b766
Revises: 68f1391d47cf
Create Date: 2026-08-17 16:01:08.317607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb481e3b766'
down_revision: Union[str, Sequence[str], None] = '68f1391d47cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_job_scores', sa.Column('score_source', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_job_scores', 'score_source')
    # ### end Alembic commands ###
