"""add score override fields

Revision ID: fa9eac278162
Revises: 330518d0cfaa
Create Date: 2026-08-14 15:14:17.065314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9eac278162'
down_revision: Union[str, Sequence[str], None] = '330518d0cfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_job_scores', sa.Column('override_score', sa.Float(), nullable=True))
    op.add_column('candidate_job_scores', sa.Column('override_note', sa.Text(), nullable=True))
    op.add_column('candidate_job_scores', sa.Column('overridden_by', sa.String(length=100), nullable=True))
    op.add_column('candidate_job_scores', sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_job_scores', 'overridden_at')
    op.drop_column('candidate_job_scores', 'overridden_by')
    op.drop_column('candidate_job_scores', 'override_note')
    op.drop_column('candidate_job_scores', 'override_score')
    # ### end Alembic commands ###
